@startuml

class Member{
e-mail:String
}

class BoardMember{
}

class Event{
date : Date
description : String
assign(I:Location):void
}

class Conference{
max_attendees:Interge
}

class BoardMeeting{
}

class Location{
description:String
addrees:String
}

class Person{
name:String
}

class AAUOC{
newLocation(I:Location):void
newEvent(e:Event):void
newPerson(p:Person):void
informEvent(e:Event):void
register(m:Member, e:Event):void
}

Event <|-- Conference
Event <|-- BoardMeeting
Conference -- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

AAUOC  o-- "0..*" Location
AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Person
Event "0..* attendsTo" -- "0..*" Member
Event"0..* isLocatedIn" --"1" Location
Conference "0..* attendsTo" -- "0..*" Person
BoardMember "0..* attendsTo" -- "0..*" BoardMeeting


@enduml