@startuml

class Member{
}

class BoardMember{
}

class Event{
}

class Conference{
}

class BoardMeeting{
}

class Location{
}

class Person{
}

class AAUOC{
}

Event <|-- Conference
Event <|-- BoardMeeting
Conference -- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

AAUOC o-- Location
AAUOC o-- Event
AAUOC o-- Person
Event -- Member
Event -- Location
Conference -- Person
BoardMember -- BoardMeeting


@enduml